<a href="https://colab.research.google.com/github/NickLawrence0025/TTA-Home-Learning/blob/main/Iris_Dataset_Deep_Learning_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

Load the data:

In [28]:
df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Split the data into x and y:

In [29]:
X = df.iloc[:,0:5].values
y = df.iloc[:,5].values

Print the numerical attributes and then the labels: 

In [30]:
print(X[0:5])
print(y[0:5])

[[1.  5.1 3.5 1.4 0.2]
 [2.  4.9 3.  1.4 0.2]
 [3.  4.7 3.2 1.3 0.2]
 [4.  4.6 3.1 1.5 0.2]
 [5.  5.  3.6 1.4 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


Confirm the split has been successful: 

In [31]:
print(X.shape)
print(y.shape)

(150, 5)
(150,)


Encode the labels:

In [32]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Print the new target labels: 

In [33]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Convert target into one hot encoding, show first few:

In [34]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


Convert X and y into train/test data - import train_test_split

In [35]:
from sklearn.model_selection import train_test_split

split the data 80/20 (20 being the test data)

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

Print the training data:

In [37]:
print(X_train[0:5])

[[138.    6.4   3.1   5.5   1.8]
 [ 85.    5.4   3.    4.5   1.5]
 [ 28.    5.2   3.5   1.5   0.2]
 [128.    6.1   3.    4.9   1.8]
 [133.    6.4   2.8   5.6   2.2]]


In [38]:
print(y_train[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]]


In [39]:
print(X_test[0:5])

[[115.    5.8   2.8   5.1   2.4]
 [ 63.    6.    2.2   4.    1. ]
 [ 34.    5.5   4.2   1.4   0.2]
 [108.    7.3   2.9   6.3   1.8]
 [  8.    5.    3.4   1.5   0.2]]


In [40]:
print(y_test[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]]


Define a sequential model:

In [41]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model

Compile the model:

In [42]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

Train the model: 

In [43]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 [==============================] - 0s 4ms/step - loss: 6.2711 - accuracy: 0.3167
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 2.3792 - accuracy: 0.2417
Epoch 3/100
3/3 [==============================] - 0s 3ms/step - loss: 1.3988 - accuracy: 0.3083
Epoch 4/100
3/3 [==============================] - 0s 3ms/step - loss: 1.3438 - accuracy: 0.4167
Epoch 5/100
3/3 [==============================] - 0s 3ms/step - loss: 1.2773 - accuracy: 0.4333
Epoch 6/100
3/3 [==============================] - 0s 4ms/step - loss: 1.3424 - accuracy: 0.4083
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 1.1981 - accuracy: 0.4250
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 1.1926 - accuracy: 0.3917
Epoch 9/100
3/3 [==============================] - 0s 3ms/step - loss: 1.1812 - accuracy: 0.4333
Epoch 10/100
3/3 [==============================] - 0s 3ms/step - loss: 1.4171 - accuracy: 0.4083
Epoch 11/100
3/3 [===========

Evaluate the model:

In [44]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.5634689331054688
Test accuracy: 0.7666666507720947


Predict the test data: 

In [45]:
y_pred = model.predict(X_test)
y_pred

array([[2.12552981e-03, 4.15441245e-01, 5.82433283e-01],
       [2.72095323e-01, 4.64321107e-01, 2.63583541e-01],
       [8.74930620e-01, 1.18111610e-01, 6.95773587e-03],
       [1.51636433e-02, 3.51314873e-01, 6.33521497e-01],
       [9.96392071e-01, 3.32669099e-03, 2.81218876e-04],
       [2.17659995e-02, 6.36052072e-01, 3.42181951e-01],
       [5.45670152e-01, 4.15517867e-01, 3.88119593e-02],
       [5.89792356e-02, 6.26036108e-01, 3.14984709e-01],
       [1.72787353e-01, 5.55337727e-01, 2.71874905e-01],
       [1.35583565e-01, 6.35267735e-01, 2.29148731e-01],
       [1.16634117e-04, 1.03398316e-01, 8.96485090e-01],
       [8.43569517e-01, 1.32516637e-01, 2.39137765e-02],
       [1.33874491e-01, 5.71302176e-01, 2.94823349e-01],
       [7.84740925e-01, 1.69878110e-01, 4.53809723e-02],
       [3.42608064e-01, 5.15244961e-01, 1.42147005e-01],
       [6.28967822e-01, 3.23066592e-01, 4.79656011e-02],
       [7.90814161e-02, 6.39069736e-01, 2.81848878e-01],
       [1.23617044e-02, 4.37859

Predict actual values and test value: 

In [46]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [2 1 0 2 0 1 0 1 1 1 2 0 1 0 1 0 1 2 1 0 2 1 0 0 2 0 0 2 2 0]
