In [3]:
import numpy as np

In [4]:
#Q.1

array = np.arange(1,10)
print(array)

[1 2 3 4 5 6 7 8 9]


In [420]:
#Q.2

lst = np.arange(1,10)
is_positive = lst > 0
x = is_positive.reshape(3,3)
print(x)

    

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [216]:
#Q.3

odd_lst = np.arange(1,10,2)
print(odd_lst)

[1 3 5 7 9]


In [433]:
#Q.4
x = np.arange(1,11)
for i in range(len(x)):
    if i % 2 == 0:
        x[i] = x[i] -1
print(x) 
    
        

[ 0  2  2  4  4  6  6  8  8 10]


In [5]:
#Q.5
two_dimension = np.arange(1,13).reshape(2,6)
print(two_dimension)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [140]:
#Q.6

a = np.arange(1,17).reshape(4,4)
b = np.arange(1,17).reshape(4,4)
c = np.dot(a,b)
column_sum = np.sum(c,axis=0)
row_sum = np.sum(c,axis=1)

print(column_sum)
print(row_sum)

[1032 1168 1304 1440]
[ 420  964 1508 2052]


In [468]:
#Q.7 (uses ONLY functions)

ones = np.ones(3)
a = np.insert(ones,[1,2,3],2)
b = np.insert(a,[2,4,6],3)
c = np.sort(b)
d = np.concatenate((c,b))
print(d)







[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


In [435]:
#Q.8
a = (1,2,3,4,5)
b = (4,5,6,7,8,9)

arr = np.delete(b,[0,1])



#Q.9
c = np.concatenate((a,b),axis=0)
d = np.sort(c)
e = d[3:8]
f = np.sum(e)
print(f)



24
